import { describe, it, expect } from 'vitest';
import { createMockToolState } from '@itsjust/core/testing';
import { gitignoreTool, buildGitignore } from '@/tool/tool-definition';
import type { GitignoreState } from '@/tool/types';

const defaultState: GitignoreState = {
  selectedTemplates: [],
  customRules: '',
  outputContent: '',
  visibilityFilter: 'all',
  searchQuery: '',
  copied: false,
};

describe('.gitignore Generator logic', () => {
  it('initializes with default state', () => {
    const state = createMockToolState<GitignoreState>(defaultState);
    expect(state.data.selectedTemplates).toEqual([]);
    expect(state.data.customRules).toBe('');
    expect(state.data.outputContent).toBe('');
  });

  it('builds .gitignore with a single template', () => {
    const result = buildGitignore(['node'], '');
    expect(result).toContain('# Node.js');
    expect(result).toContain('node_modules/');
    expect(result).toContain('# .gitignore — Generated by .gitignore Generator');
    expect(result).not.toContain('# Python');
  });

  it('builds .gitignore with multiple templates', () => {
    const result = buildGitignore(['node', 'python'], '');
    expect(result).toContain('# Node.js');
    expect(result).toContain('# Python');
    expect(result).toContain('node_modules/');
    expect(result).toContain('__pycache__/');
  });

  it('includes custom rules when provided', () => {
    const result = buildGitignore(['node'], 'my-secrets/\n*.local');
    expect(result).toContain('# Custom rules');
    expect(result).toContain('my-secrets/');
    expect(result).toContain('*.local');
  });

  it('generates output with macOS template', () => {
    const result = buildGitignore(['macos'], '');
    expect(result).toContain('# macOS');
    expect(result).toContain('.DS_Store');
    expect(result).toContain('.Spotlight-V100');
  });

  it('generates output with IDE templates', () => {
    const result = buildGitignore(['vscode', 'jetbrains'], '');
    expect(result).toContain('VS Code');
    expect(result).toContain('JetBrains');
    expect(result).toContain('.vscode/settings.json');
    expect(result).toContain('.idea/');
  });

  it('appends a trailing newline', () => {
    const result = buildGitignore(['node'], '');
    expect(result.endsWith('\n')).toBe(true);
  });

  it('handles empty selection gracefully', () => {
    const result = buildGitignore([], '');
    expect(result).toContain('# .gitignore — Generated by');
    expect(result.split('\n').filter((l) => l.trim() && !l.startsWith('#')).length).toBe(0);
  });

  it('handles custom rules without any templates', () => {
    const result = buildGitignore([], 'custom-rule/\n*.secret');
    expect(result).toContain('# Custom rules');
    expect(result).toContain('custom-rule/');
    expect(result).toContain('*.secret');
  });
});

describe('.gitignore Generator deserialize', () => {
  it('accepts valid state object', () => {
    const result = gitignoreTool.deserialize(defaultState);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.selectedTemplates).toEqual([]);
    }
  });

  it('rejects null data', () => {
    const result = gitignoreTool.deserialize(null);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('Invalid data');
    }
  });

  it('rejects non-object data', () => {
    const result = gitignoreTool.deserialize('string');
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('Invalid data');
    }
  });

  it('rejects object without required fields', () => {
    const result = gitignoreTool.deserialize({ someField: 'value' });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('Invalid data');
    }
  });

  it('serializes state to JSON string', () => {
    const json = gitignoreTool.serialize(defaultState);
    expect(() => JSON.parse(json)).not.toThrow();
    const parsed = JSON.parse(json);
    expect(parsed.selectedTemplates).toEqual([]);
    expect(parsed.customRules).toBe('');
  });

  it('round-trips state through serialize/deserialize', () => {
    const stateWithData: GitignoreState = {
      ...defaultState,
      selectedTemplates: ['node', 'python'],
      customRules: 'my-rule/',
      outputContent: 'some content',
      visibilityFilter: 'language',
      searchQuery: 'node',
    };
    const json = gitignoreTool.serialize(stateWithData);
    const parsed = JSON.parse(json);
    const result = gitignoreTool.deserialize(parsed);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.selectedTemplates).toEqual(['node', 'python']);
      expect(result.data.customRules).toBe('my-rule/');
      expect(result.data.visibilityFilter).toBe('language');
    }
  });
});

describe('buildGitignore with specific templates', () => {
  it('generates comprehensive output for common stacks', () => {
    const result = buildGitignore(['node', 'react', 'vscode', 'macos', 'windows'], '');
    expect(result).toContain('Node.js');
    expect(result).toContain('React');
    expect(result).toContain('VS Code');
    expect(result).toContain('macOS');
    expect(result).toContain('Windows');
    expect(result).toContain('node_modules/');
    expect(result).toContain('dist/');
    expect(result).toContain('.DS_Store');
    expect(result).toContain('Thumbs.db');
  });

  it('generates Python/Django stack', () => {
    const result = buildGitignore(['python', 'django'], '');
    expect(result).toContain('# Python');
    expect(result).toContain('# Django');
    expect(result).toContain('venv/');
    expect(result).toContain('__pycache__/');
    expect(result).toContain('db.sqlite3');
    expect(result).toContain('media/');
  });

  it('generates Go output', () => {
    const result = buildGitignore(['go'], '');
    expect(result).toContain('# Go');
    expect(result).toContain('*.exe');
    expect(result).toContain('bin/');
  });

  it('generates Rust output', () => {
    const result = buildGitignore(['rust'], '');
    expect(result).toContain('# Rust');
    expect(result).toContain('target/');
    expect(result).toContain('Cargo.lock');
  });

  it('generates Java output', () => {
    const result = buildGitignore(['java'], '');
    expect(result).toContain('# Java');
    expect(result).toContain('*.class');
    expect(result).toContain('*.jar');
    expect(result).toContain('target/');
  });

  it('generates Terraform output', () => {
    const result = buildGitignore(['terraform'], '');
    expect(result).toContain('# Terraform');
    expect(result).toContain('.terraform/');
    expect(result).toContain('*.tfstate');
  });

  it('generates Docker output', () => {
    const result = buildGitignore(['docker'], '');
    expect(result).toContain('# Docker');
    expect(result).toContain('.docker/');
  });

  it('generates Flutter output', () => {
    const result = buildGitignore(['flutter'], '');
    expect(result).toContain('# Flutter');
    expect(result).toContain('.dart_tool/');
    expect(result).toContain('build/');
  });

  it('generates combined JetBrains/Unity/Godot output', () => {
    const result = buildGitignore(['jetbrains', 'unity', 'godot'], '');
    expect(result).toContain('JetBrains');
    expect(result).toContain('Unity');
    expect(result).toContain('Godot');
    expect(result).toContain('.idea/');
    expect(result).toContain('Library/');
  });

  it('generates Deno output', () => {
    const result = buildGitignore(['deno'], '');
    expect(result).toContain('# Deno');
    expect(result).toContain('.deno/');
    expect(result).toContain('deno.lock');
  });

  it('generates Bun output', () => {
    const result = buildGitignore(['bun'], '');
    expect(result).toContain('# Bun');
    expect(result).toContain('bun.lock');
    expect(result).toContain('node_modules/');
  });

  it('generates Solid.js output', () => {
    const result = buildGitignore(['solidjs'], '');
    expect(result).toContain('# Solid.js');
    expect(result).toContain('.solid/');
    expect(result).toContain('dist/');
  });

  it('generates Tailwind CSS output', () => {
    const result = buildGitignore(['tailwindcss'], '');
    expect(result).toContain('# Tailwind CSS');
    expect(result).toContain('.tailwind-cache/');
  });

  it('generates FastAPI output', () => {
    const result = buildGitignore(['fastapi'], '');
    expect(result).toContain('# FastAPI');
    expect(result).toContain('__pycache__');
    expect(result).toContain('.venv/');
  });

  it('generates NestJS output', () => {
    const result = buildGitignore(['nestjs'], '');
    expect(result).toContain('# NestJS');
    expect(result).toContain('.nest/');
    expect(result).toContain('dist/');
  });

  it('generates Remix output', () => {
    const result = buildGitignore(['remix'], '');
    expect(result).toContain('# Remix');
    expect(result).toContain('public/build/');
    expect(result).toContain('build/');
  });

  it('generates ESLint output', () => {
    const result = buildGitignore(['eslint'], '');
    expect(result).toContain('# ESLint');
    expect(result).toContain('.eslintcache');
  });

  it('generates Prettier output', () => {
    const result = buildGitignore(['prettier'], '');
    expect(result).toContain('# Prettier');
    expect(result).toContain('.prettiercache');
  });

  it('generates combined Tailwind + React + ESLint + Prettier stack', () => {
    const result = buildGitignore(['tailwindcss', 'react', 'eslint', 'prettier'], '');
    expect(result).toContain('Tailwind CSS');
    expect(result).toContain('React');
    expect(result).toContain('ESLint');
    expect(result).toContain('Prettier');
    expect(result).toContain('.eslintcache');
    expect(result).toContain('.prettiercache');
    expect(result).toContain('.tailwind-cache/');
  });
});
