import type { Tool } from '@itsjust/core';
import toolConfig from './tool.config';
import type { GitignoreState, GitignoreTemplate } from './types';

function isGitignoreState(value: unknown): value is GitignoreState {
  if (typeof value !== 'object' || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    Array.isArray(v.selectedTemplates) &&
    typeof v.customRules === 'string' &&
    typeof v.outputContent === 'string'
  );
}

// Template definitions — each returns the .gitignore content for that template
// Keyed by GitignoreTemplate id, each value is an array of lines to include.
// The first line should be a comment (# Name) describing the template.
/**
 * Map of gitignore template rules, keyed by template ID.
 * Each entry is an array of lines (comments and rules) to include
 * when that template is selected.
 */
const TEMPLATE_RULES: Record<GitignoreTemplate, string[]> = {
  // Languages
  node: [
    '# Node.js',
    'node_modules/',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'pnpm-debug.log*',
    '.pnpm-store/',
    'lerna-debug.log*',
    '.npm/',
    '.yarn/',
    '.yarnrc.yml',
    'yarn.lock',
    'package-lock.json',
    'pnpm-lock.yaml',
  ],
  python: [
    '# Python',
    '__pycache__/',
    '*.py[cod]',
    '*$py.class',
    '*.so',
    '.Python',
    'env/',
    'venv/',
    '.venv/',
    'env.bak/',
    'venv.bak/',
    '.env/',
    '.pytest_cache/',
    '.mypy_cache/',
    '.ruff_cache/',
    '.hypothesis/',
    '*.egg-info/',
    '*.egg',
    'dist/',
    'build/',
    '*.whl',
    'MANIFEST',
    'pip-log.txt',
    'pip-delete-this-directory.txt',
    '.tox/',
    '.nox/',
    '.coverage',
    'coverage/',
    'coverage.xml',
    'htmlcov/',
    '__pypackages__/',
  ],
  java: [
    '# Java',
    '*.class',
    '*.jar',
    '*.war',
    '*.nar',
    '*.ear',
    '*.zip',
    '*.tar.gz',
    '*.rar',
    'hs_err_pid*',
    'replay_pid*',
    'target/',
    'build/',
    '!.mvn/wrapper/maven-wrapper.jar',
    '.gradle/',
    'build.gradle',
    '.classpath',
    '.project',
    '.settings/',
    '.idea/',
    '*.iws',
    'out/',
    '*.log',
  ],
  rust: [
    '# Rust',
    'target/',
    '**/*.rs.bk',
    'Cargo.lock',
  ],
  go: [
    '# Go',
    '*.exe',
    '*.exe~',
    '*.dll',
    '*.so',
    '*.dylib',
    '*.test',
    '*.out',
    'bin/',
    'vendor/',
    'go.work.sum',
  ],
  ruby: [
    '# Ruby',
    '*.gem',
    '*.rbc',
    '.bundle/',
    'vendor/bundle/',
    'vendor/.bundle/',
    'Gemfile.lock',
    '.ruby-version',
    '.ruby-gemset',
    '.rvmrc',
    '.byebug_history',
    'log/',
    'tmp/',
  ],
  dotnet: [
    '# .NET',
    '**/bin/',
    '**/obj/',
    '*.user',
    '*.suo',
    '*.userosscache',
    '*.sln.docstates',
    'packages/',
    '*.nupkg',
    '.nuget/',
    '**/[Pp]ublish/',
    '*.DotSettings.user',
  ],
  c: [
    '# C',
    '*.o',
    '*.obj',
    '*.exe',
    '*.out',
    '*.app',
    '*.dll',
    '*.dylib',
    '*.lib',
    '*.pdb',
    'build/',
    'Build/',
  ],
  cpp: [
    '# C++',
    '*.o',
    '*.obj',
    '*.exe',
    '*.out',
    '*.app',
    '*.dll',
    '*.dylib',
    '*.lib',
    '*.pdb',
    '*.ilk',
    '*.exp',
    'build/',
    'Build/',
    '.deps/',
    'Debug/',
    'Release/',
  ],
  swift: [
    '# Swift',
    '.build/',
    'Packages/',
    '*.swp',
    '*.swo',
    '*.xcworkspace',
    'xcuserdata/',
    'DerivedData/',
    '.swiftpm/',
    'build/',
  ],
  kotlin: [
    '# Kotlin',
    '.kotlin_module',
    'build/',
    'target/',
    '*.class',
    '*.jar',
    '.gradle/',
    'local.properties',
  ],
  scala: [
    '# Scala',
    'target/',
    '*.class',
    '*.jar',
    '.bsp/',
    '.metals/',
    '.bloop/',
    '.scala-build/',
    '*.log',
  ],
  elixir: [
    '# Elixir',
    '_build/',
    'deps/',
    '*.ez',
    'erl_crash.dump',
    '.elixir_ls/',
    'mix.lock',
    '.fetch',
  ],
  haskell: [
    '# Haskell',
    'dist/',
    'dist-newstyle/',
    '.stack-work/',
    '*.hi',
    '*.hie',
    '.cabal-sandbox/',
    'cabal.sandbox.config',
    'cabal.project.local',
    '.ghc.environment.*',
  ],
  julia: [
    '# Julia',
    'Manifest.toml',
    'LocalPreferences.toml',
    '*.cov',
    '*.jl.cov',
    '.cov/',
    'docs/build/',
    'docs/site/',
  ],
  lua: [
    '# Lua',
    '*.luac',
    'build/',
    '*.rock',
    '.luarocks/',
  ],
  perl: [
    '# Perl',
    'blib/',
    '_build/',
    'Build',
    'Makefile',
    'Makefile.old',
    '*.o',
    'cover_db/',
    'inc/',
    'MYMETA.*',
  ],
  r: [
    '# R',
    '.Rhistory',
    '.RData',
    '.Rproj.user',
    '.Renviron',
    '.Renviron.site',
    '.Rprofile',
    '.Rcheck/',
    '*-Ex.R',
    '*.Rout',
    '*.Rbin',
    'src/*.o',
    'src/*.so',
    'src/*.dll',
  ],
  matlab: [
    '# MATLAB',
    '*.asv',
    '*.m~',
    '*.mat~',
    '*.fig~',
    'slprj/',
    'Simulink/',
    'coderepo/',
    'xcp/',
  ],
  zig: [
    '# Zig',
    'zig-out/',
    '.zig-cache/',
    '*.o',
    '*.obj',
    '*.pdb',
    '*.exe',
    '*.out',
    '*.wasm',
    '*.log',
  ],
  crystal: [
    '# Crystal',
    '.crystal/',
    'lib/',
    'bin/',
    '*.dwarf',
    '*.crystal-*',
    '.shards/',
    'shards.lock',
  ],

  // Frameworks
  react: [
    '# React (CRA / Vite)',
    'node_modules/',
    'build/',
    'dist/',
    '.env.local',
    '.env.development.local',
    '.env.test.local',
    '.env.production.local',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
  ],
  nextjs: [
    '# Next.js',
    '.next/',
    'out/',
    'build/',
    'node_modules/',
    '.env*.local',
    '.vercel/',
    '*.tsbuildinfo',
    'next-env.d.ts',
  ],
  vue: [
    '# Vue',
    'dist/',
    'node_modules/',
    '*.log',
    '.env.local',
    '.env.*.local',
  ],
  nuxt: [
    '# Nuxt',
    '.nuxt/',
    'dist/',
    'node_modules/',
    '.output/',
    '.env',
    '.env.*',
    '*.log',
  ],
  svelte: [
    '# Svelte / SvelteKit',
    'build/',
    '.svelte-kit/',
    'node_modules/',
    'package/',
    '.env',
    '.env.*',
    '*.log',
  ],
  angular: [
    '# Angular',
    'dist/',
    '.angular/',
    'node_modules/',
    '*.log',
    '.env.local',
    'tmp/',
  ],
  gatsby: [
    '# Gatsby',
    'public/',
    '.cache/',
    'node_modules/',
    '*.log',
    '.env.development',
    '.env.production',
  ],
  eleventy: [
    '# Eleventy',
    '_site/',
    '.cache/',
    'node_modules/',
    '*.log',
  ],
  django: [
    '# Django',
    '*.pyc',
    '__pycache__/',
    '*.pyo',
    '*.sqlite3',
    'media/',
    'staticfiles/',
    'static_root/',
    '.env',
    'local_settings.py',
    'db.sqlite3',
    '*.pot',
    '*.mo',
  ],
  rails: [
    '# Ruby on Rails',
    'tmp/',
    'log/',
    'storage/',
    'vendor/bundle/',
    '.bundle/',
    'public/packs/',
    'public/assets/',
    '.byebug_history',
    '.DS_Store',
    '*.sqlite3',
    'yarn-error.log',
    '.ruby-gemset',
  ],
  laravel: [
    '# Laravel',
    'vendor/',
    'node_modules/',
    '.env',
    '.env.*',
    '*.log',
    'storage/',
    'public/storage/',
    'public/hot',
    'bootstrap/cache/',
  ],
  spring: [
    '# Spring Boot',
    'target/',
    '.mvn/',
    '*.jar',
    '*.war',
    '*.ear',
    '*.log',
    '.sts4-cache/',
    'HELP.md',
    '!**/src/main/**/target/',
    '!**/src/test/**/target/',
  ],
  sass: [
    '# Sass',
    '.sass-cache/',
    '*.css.map',
    '*.sass.map',
    '*.scss.map',
  ],

  // IDEs & Editors
  vscode: [
    '# VS Code',
    '.vscode/settings.json',
    '.vscode/launch.json',
    '.vscode/tasks.json',
    '.vscode/*.code-snippets',
    '!.vscode/extensions.json',
    '!.vscode/*.code-snippets',
    '.history/',
  ],
  jetbrains: [
    '# JetBrains IDEs',
    '.idea/',
    '*.iml',
    '*.iws',
    '.idea_modules/',
    'atlassian-ide-plugin.xml',
    '.gradle/',
    'build/',
  ],
  vim: [
    '# Vim',
    '*.swp',
    '*.swo',
    '*~',
    '.vim/',
    '.netrwhist',
    'Session.vim',
    '.viminfo',
  ],
  emacs: [
    '# Emacs',
    '*~',
    '#*#',
    '.#*',
    '.emacs.desktop',
    '.emacs.desktop.lock',
    '.auto-save-list/',
    'tramp/',
    '.org-id-locations/',
    '*_archive/',
    'auto-save-list/',
  ],
  visualstudio: [
    '# Visual Studio',
    '.vs/',
    '*.suo',
    '*.user',
    '*.userosscache',
    '*.sln.docstates',
    '*.userprefs',
    '**/bin/',
    '**/obj/',
    '**/[Pp]ublish/',
    '*.nupkg',
    'packages/',
  ],
  xcode: [
    '# Xcode',
    '*.xcworkspace',
    'xcuserdata/',
    'DerivedData/',
    '*.hmap',
    '*.ipa',
    '*.dSYM.zip',
    '*.dSYM',
    'build/',
    '.build/',
  ],

  // Operating Systems
  macos: [
    '# macOS',
    '.DS_Store',
    '._*',
    '.Spotlight-V100',
    '.Trashes',
    '.fseventsd',
    '.AppleDouble',
    '.apdisk',
    '.AppleDB',
    '.com.apple.timemachine.donotpresent',
  ],
  windows: [
    '# Windows',
    'Thumbs.db',
    'Thumbs.db:encryptable',
    'ehthumbs.db',
    'ehthumbs_vista.db',
    '*.stackdump',
    '[Dd]esktop.ini',
    '$RECYCLE.BIN/',
    '*.lnk',
  ],
  linux: [
    '# Linux',
    '*~',
    '.fuse_hidden*',
    '.directory',
    '.Trash-*',
    '.nfs*',
  ],

  // Platforms & Tools
  android: [
    '# Android',
    '.gradle/',
    'build/',
    'local.properties',
    '*.iml',
    '.idea/',
    '.navigation/',
    'captures/',
    '.externalNativeBuild/',
    '*.apk',
    '*.aab',
    '*.dex',
    '*.class',
    'bin/',
    'gen/',
    'out/',
    '.gradletasknamecache',
  ],
  flutter: [
    '# Flutter',
    '.dart_tool/',
    'build/',
    '.flutter-plugins',
    '.flutter-plugins-dependencies',
    '.packages',
    '.pub/',
    'pubspec.lock',
    '.metadata',
    '*.iml',
    '.idea/',
    '.vscode/',
    '*.log',
    '*.aot',
    '.android/',
    '.ios/',
    'coverage/',
  ],
  docker: [
    '# Docker',
    '.docker/',
    '.env',
    '*.tar',
    '*.tar.gz',
    '*.tgz',
  ],
  terraform: [
    '# Terraform',
    '.terraform/',
    '*.tfstate',
    '*.tfstate.*',
    '*.tfplan',
    '*.terraform.lock.hcl',
    '.terraformrc',
    'terraform.rc',
    'crash.log',
    'crash.*.log',
    'override.tf',
    'override.tf.json',
    '_override.tf',
  ],
  ansible: [
    '# Ansible',
    '*.retry',
    'inventory/',
    '.ansible/',
    '*.log',
  ],
  unity: [
    '# Unity',
    'Library/',
    'Temp/',
    'Build/',
    'Builds/',
    'obj/',
    '*.pidb',
    '*.unityproj',
    '*.sln',
    '*.csproj',
    '*.userprefs',
    '*.apk',
    '*.ipa',
    '*.unitypackage',
    'sysinfo.txt',
  ],
  unrealengine: [
    '# Unreal Engine',
    'DerivedDataCache/',
    'Intermediate/',
    'Saved/',
    'Binaries/',
    'Build/',
    '.vs/',
    '*.sln',
    '*.suo',
    '*.vcxproj',
    '*.opensdf',
    '*.user',
    '*.xcodeproj',
    'Content/Paks/',
  ],
  godot: [
    '# Godot',
    '.godot/',
    'export/',
    '*.translation',
    '*.import',
    '.mono/',
    'data_*',
    '.fbm_*',
  ],
  jekyll: [
    '# Jekyll',
    '_site/',
    '.jekyll-cache/',
    '.jekyll-metadata',
    'Gemfile.lock',
    '.sass-cache/',
  ],
  hugo: [
    '# Hugo',
    'public/',
    'resources/',
    '.hugo_build.lock',
  ],
  gitbook: [
    '# GitBook',
    '_book/',
    'book/',
    'node_modules/',
    '*.log',
  ],
  deno: [
    '# Deno',
    '.deno/',
    'deno.lock',
    'lock.json',
    'dist/',
    'build/',
    '*.wasm',
  ],
  bun: [
    '# Bun',
    'bun.lock',
    'bun.lockb',
    'node_modules/',
    '*.log',
  ],
  solidjs: [
    '# Solid.js',
    'node_modules/',
    'dist/',
    'build/',
    'dev-dist/',
    '.env',
    '.env.*',
    '*.log',
    '.solid/',
    'public/build/',
  ],
  gradle: [
    '# Gradle',
    '.gradle/',
    'build/',
    '!gradle/wrapper/gradle-wrapper.jar',
    '!**/src/main/**/build/',
    '!**/src/test/**/build/',
    '*.class',
    '*.jar',
    '*.war',
    '*.nar',
    '*.ear',
    '*.zip',
    '*.tar.gz',
    '*.rar',
    'local.properties',
    '.gradletasknamecache',
    'generated/',
  ],

  // Package Managers
  pnpm: [
    '# pnpm',
    '.pnpm-store/',
    'pnpm-debug.log*',
    'pnpm-lock.yaml',
  ],

  // Testing Frameworks
  playwright: [
    '# Playwright',
    '/test-results/',
    '/playwright-report/',
    '/blob-report/',
    '/playwright/.cache/',
  ],

  // Linters & Formatters
  biome: [
    '# Biome',
    '.biome/',
    'node_modules/',
    'dist/',
    '*.log',
  ],
};

/**
 * Build a complete .gitignore file content string from selected templates
 * and optional custom rules.
 *
 * Generates a header comment with date and tool attribution, then appends
 * each selected template's rules (grouped by template), followed by any
 * custom rules provided by the user.
 *
 * @param selectedTemplates - Array of template IDs to include
 * @param customRules - Raw string of custom .gitignore rules (one per line)
 * @returns The complete .gitignore content as a string, with trailing newline
 */
function buildGitignore(selectedTemplates: GitignoreTemplate[], customRules: string): string {
  const lines: string[] = [];

  lines.push('# .gitignore — Generated by .gitignore Generator');
  lines.push(`# https://gitignore-generator.itsjust.tools`);
  lines.push(`# ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // Add template entries
  for (const templateId of selectedTemplates) {
    const rules = TEMPLATE_RULES[templateId];
    if (rules && rules.length > 0) {
      const lastLine = lines[lines.length - 1];
      if (lastLine !== undefined && !lastLine.startsWith('#')) {
        lines.push('');
      }
      lines.push(...rules);
    }
  }

  // Add custom rules
  if (customRules.trim()) {
    lines.push('');
    lines.push('# Custom rules');
    lines.push(...customRules.split('\n').map((l) => l.trim()).filter(Boolean));
  }

  lines.push('');
  return lines.join('\n');
}

export const gitignoreTool: Tool<GitignoreState> = {
  id: toolConfig.id,
  name: toolConfig.name,
  version: toolConfig.version,
  config: toolConfig,
  initialState: {
    selectedTemplates: [],
    customRules: '',
    outputContent: '',
    visibilityFilter: 'all',
    searchQuery: '',
    copied: false,
  },
  serialize: (state) => JSON.stringify(state, null, 2),
  deserialize: (data) => {
    if (isGitignoreState(data)) {
      return { success: true, data };
    }
    return {
      success: false,
      error: 'Invalid data format: expected GitignoreState object',
    };
  },
  exporters: [
    {
      format: 'json',
      loader: () => import('./exporters/json'),
    },
  ],
};

export { buildGitignore };
export { TEMPLATE_RULES };
