import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import type { ReactNode } from 'react';
import manifest from '@/app/manifest';
import robots from '@/app/robots';
import sitemap from '@/app/sitemap';
import ErrorPage from '@/app/error';
import NotFound from '@/app/not-found';
import { JsonLd } from '@/app/json-ld';
import ToolPage from '@/app/page';
import { cn } from '@/lib/utils';
import { generateJsonLd, generateToolMetadata } from '@/lib/seo';
import toolConfig from '@/tool/tool.config';
import { getPublicSiteUrl, templateMetadata } from '@/tool/template-metadata';
import { gitignoreTool, buildGitignore } from '@/tool/tool-definition';
import { ToolCanvas } from '@/tool/components/tool-canvas';
import { ToolSidebar } from '@/tool/components/tool-sidebar';
import { ToolToolbar } from '@/tool/components/tool-toolbar';
import type { GitignoreState } from '@/tool/types';
import { TEMPLATES } from '@/tool/types';

vi.mock('next/link', () => ({
  default: ({ href, children, ...props }: { href: string; children: ReactNode }) => (
    <a href={href} {...props}>
      {children}
    </a>
  ),
}));

vi.mock('@/app/tool-client-wrapper', () => ({
  default: () => <div data-testid="tool-client-wrapper">tool-client-wrapper</div>,
}));

describe('app and seo', () => {
  const getOgImageUrl = (
    images: NonNullable<NonNullable<ReturnType<typeof generateToolMetadata>['openGraph']>['images']>
  ): string | undefined => {
    const list = Array.isArray(images) ? images : [images];
    const first = list[0];
    if (!first) return undefined;
    if (typeof first === 'string') return first;
    if (first instanceof URL) return first.toString();
    return String(first.url);
  };

  it('builds metadata and json-ld values', () => {
    const metadata = generateToolMetadata(toolConfig);
    const jsonLd = generateJsonLd(toolConfig);

    expect(metadata.creator).toBe(toolConfig.name);
    expect(metadata.metadataBase?.toString()).toBe('http://localhost:3000/');
    const ogUrl = metadata.openGraph?.images ? getOgImageUrl(metadata.openGraph.images) : undefined;
    expect(ogUrl).toContain('/og.svg');
    expect(jsonLd.url).toBe('http://localhost:3000');
    expect(jsonLd.featureList.length).toBeGreaterThan(0);
  });

  it('returns site manifest, robots and sitemap', () => {
    const man = manifest();
    const rob = robots();
    const sm = sitemap();

    expect(man.name).toBe(templateMetadata.appName);
    expect(rob.sitemap).toBe('http://localhost:3000/sitemap.xml');
    expect(sm[0]?.url).toBe('http://localhost:3000');
  });

  it('renders json-ld script safely', () => {
    render(<JsonLd config={{ ...toolConfig, name: '</script>' }} />);
    const script = document.querySelector('script[type="application/ld+json"]');
    expect(script?.innerHTML).toContain('\\u003c/script>');
  });

  it('renders error page and invokes reset', () => {
    const reset = vi.fn();
    render(<ErrorPage error={new Error('boom')} reset={reset} />);

    expect(screen.getByText('Something went wrong')).toBeInTheDocument();
  });

  it('renders not-found page', () => {
    render(<NotFound />);
    expect(screen.getByText('Page not found')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Go home' })).toHaveAttribute('href', '/');
  });

  it('renders top-level tool page', () => {
    render(<ToolPage />);
    expect(screen.getByTestId('tool-client-wrapper')).toBeInTheDocument();
    expect(document.querySelector('script[type="application/ld+json"]')).toBeInTheDocument();
  });

  it('covers tool definition and helper exports', async () => {
    expect(cn('a', undefined, 'b', false, null, 'c')).toBe('a b c');
    expect(getPublicSiteUrl()).toBe('http://localhost:3000');

    // buildGitignore test
    const result = buildGitignore(['node'], '');
    expect(result).toContain('node_modules/');
    expect(result).toContain('Generated by');

    // deserialize
    const validState: GitignoreState = {
      selectedTemplates: [],
      customRules: '',
      outputContent: '',
      visibilityFilter: 'all',
      searchQuery: '',
      copied: false,
    };
    expect(gitignoreTool.deserialize(validState)).toEqual({
      success: true,
      data: validState,
    });
    expect(gitignoreTool.deserialize({ nope: true })).toEqual({
      success: false,
      error: 'Invalid data format: expected GitignoreState object',
    });
    expect(gitignoreTool.serialize(validState)).toContain('"selectedTemplates"');
  });

  it('exports TEMPLATES from types', () => {
    const templateIds = TEMPLATES.map((t) => t.id);
    expect(templateIds).toContain('node');
    expect(templateIds).toContain('python');
    expect(templateIds).toContain('react');
    expect(templateIds).toContain('vscode');
    expect(templateIds).toContain('macos');
    expect(templateIds.length).toBeGreaterThanOrEqual(50);
  });

  it('renders tool components', () => {
    const mockState: GitignoreState = {
      selectedTemplates: [],
      customRules: '',
      outputContent: '',
      visibilityFilter: 'all',
      searchQuery: '',
      copied: false,
    };

    render(
      <>
        <ToolToolbar />
        <ToolSidebar
          state={mockState}
          onToggleTemplate={() => {}}
          onCustomRulesChange={() => {}}
          onFilterChange={() => {}}
          onSearchChange={() => {}}
          onGenerate={() => {}}
          onClear={() => {}}
        />
        <ToolCanvas state={mockState} />
      </>
    );

    expect(screen.getByRole('application', { name: '.gitignore Generator' })).toBeInTheDocument();
    expect(screen.getByText('Select templates below to generate a .gitignore file')).toBeInTheDocument();
  });
});
